.eslintrc.js, .gitignore, package.json
- It contains eslint setup configuration
- add eslint package
- initialize eslint
- add style guide rules
none
- PT Story link - `[#165596308] (https://www.pivotaltracker.com/story/show/165596308)`
=> #165596308 setup eslint configuration

.gitignore, .jshintrc, README.md, env.sample, package.json, server/index.js
- This PR will initialize the express server with environment variables
- update package.json file with dotenv, express, and nodemon packages
- add .env file to specify PORT number
- add server/index.js to create the server
- update package.json file with development and production scripts
- update README.md file with instructions on how to run the project
1. Clone the repo.
2. Switch to project directory
3. Type ``npm install`` to install dependencies
4. Type ``npm run dev`` to start development server or npm start to run in production
[165717406](https://www.pivotaltracker.com/story/show/165717406)
=> #165717406: Initialize the express server with environment variables

README.md
- It updates the readme with Hound CI badge
- add badge markdown to the readme
none
- PT Story link - `[#165596309] (https://www.pivotaltracker.com/story/show/165596309)`
=> #165596309 add Hound CI badge to readme

package.json, server/index.js, swagger.json
- It contains setup API documentation using Swagger
- install swagger-ui-express package
- add configurations to index.js
- add swagger.json file
``npm install``
- Add a .env file with a specific `{PORT}` number
- Launch the node server with
``npm run dev``
- Open a browser and visit
`` http://localhost:{PORT}/api-docs``
none
- PT Story link - `[#165596313] (https://www.pivotaltracker.com/story/show/165596313)`
=> #165596313 setup API documentation using Swagger

.editorconfig, .eslintrc.js, README.md, knexfile.js, package.json, server/index.js, server/migrations/20190501142532_create_users_table.js, server/models/User.js, test/index.spec.js
- This PR will setup prettier with lint staged
- add .editorconfig file
- update .eslintrc.js
- add husky, lint-staged, prettier-eslint and prettier-eslint-cli packages
- add lint, lint:fix scripts
- add husky and lint-staged hooks to package.json
- clone the repo and cd into it
- use "npm install" to install dependencies
- use "npm run dev" to start the server in development
[165762877](https://www.pivotaltracker.com/story/show/165762877)
=> #165762877 Setup prettier with lint staged

.eslintrc.js, .travis.yml, app.json, knexfile.js, package.json, server/index.js, server/middlewares/controllers/authController.js, server/middlewares/validators/authValidator.js, server/models/User.js, server/routes/v1/auth.js, server/utils/validationUtils.js, swagger.json, test/auth.spec.js, test/index.spec.js
- sends detailed signup error/success validation messages
- Install indicative to handle in request body validation.
- Install body-parser to help parse request to json.
- Export express app and knex database connection from index.js.
- Create Test for index.js host get request.
- Create Test for auth sign up route.
- Create auth sign up route and auth validator middleware.
- Add required env variables in app.json for heroku review app
- Update swagger doc to contain auth route and Add heroku post build
script.
- Add necessary fields in travis.yaml
- Install bcrypt and encrypt password.
``npm i``
- set NODE_ENV to test
- To run local tests using mocha
``npm test``
- test are written are …
=> feat: send detailed signup error/success messages

package.json, server/index.js, server/middlewares/controllers/authorController.js, server/middlewares/validators/authorValidator.js, server/migrations/20190504012140_create_authors_table.js, server/models/Author.js, server/routes/v1/author.js, test/auth.spec.js, test/index.spec.js
User can add authors
- Add test for authors
- Add authConttroller in middleware/controller
- Add migration/create_authors_table
- Add models/Authors
- Add validator/authValidator
1. Clone the repo and cd into it
2. Use **npm install** to install dependencies
3. Add all necessary environment variables in your local .env file using the .env.sample file
4. Create the databases locally and run the migrations command for development and test
5. **npm run test** to run tests
6. **npm run dev** to run the project locally on your machine
Provide all the needed environment variables and ensure run migrations
#165764173
=> #165764173 User can add  authors 

package.json, server/middlewares/controllers/authController.js, test/auth.spec.js
Implements generation of token for a user on successful registration
- added jsowebtoken to package.json
- implemented token generation on successful signup in authController.signUp
- updated signup route test to check for token
http://localhost:5000/api/v1/auth/signup
None
None
=> #165596315 User Receives Token on Sucessful Registration

package.json, server/models/User.js, swagger.json
- This PR will update swagger API documentation
- update package.json white bcryptjs
- update bcrypt import in server/models/User.js
- update swagger.json
- Clone the repo and cd into it
- use "npm install " to install dependencies
- use "npm run dev" to start server in development 
- assess `http://localhost:{PORT}/api-docs/` to test routes
[165837811](https://www.pivotaltracker.com/story/show/165837811)
=> #165837811: bg(fix) Update swagger API documentation

package.json, server/index.js, server/middlewares/controllers/authorController.js, server/middlewares/validators/authorValidator.js, server/routes/v1/author.js, test/auth.spec.js, test/author.spec.js, test/helpers/mail.spec.js
- implement read, update and delete functionalities for authors
- Move and modify create author test from auth.spec.js
to author.spec.js.
- Write test for read update and delete author.
- Create routes for read, update, and delete author.
- Write validation and controllers for each route.
- Add --exit to package.json.
- Modify author route definition in index.js to allow uniformity.
- Skip all mail test, till further notice.
``npm i``
- set NODE_ENV to test
- To run local tests using mocha
``npm test``
- test are written are simple just enough to pass
- PT Story link - https://www.pivotaltracker.com/story/show/165880237
=> #165880237 complete author route crud

mails/welcome-mail/welcome-mail.html.hbs, mails/welcome-mail/welcome-mail.text.hbs, server/middlewares/controllers/authController.js, server/migrations/20190501142532_create_users_table.js, server/routes/v1/auth.js, test/auth.spec.js
Implement the feature for email verification 
- Include verification link in welcome message
- Create endpoint "/api/v1/auth/verify/:verificationCode" to handle verification
- Add test codes for the above feature
- Clone the repo, cd into epic-mail-application
- Run this command 'npm run dev'
- After a successful registration
- Get the link from your mail inbox
- Using postman with a post method go to the above link
<a href = "https://www.pivotaltracker.com/story/show/165879964">#165879964</a>
=> #165879964: Implement email account verification

server/middlewares/controllers/bookController.js, server/middlewares/validators/bookValidator.js, server/routes/v1/books.js, test/books.spec.js
To implement view and delete books functionality
- implemented get all books functionality in bookController.getAllBooks
- implemented get a book functionality in bookController.getSingleBook
- implemented delete a book functionality in bookController.deleteSingleBook
- declared the functionalities api endpoint route in books
- implemented tests for the functionalites
-implemented validation for the delete and via single book endpoints in bookValidation.getBookValidation
GET http://localhost:5000/api/v1/books
GET http://localhost:5000/api/v1/books/<book_id>
DELETE http://localhost:5000/api/v1/books/<book_id>
None
None
=> #165880209  User should be able to view and delete books

.gitignore, test/__snapshots__/books.spec.js.snap, test/books.spec.js
Refactors tests for books endpoints on api/v1/books
- removes mocha, chai and chai-http used for 
- migrates tests to employ jest and supertest for 
- adds files to .gitignore
- Clone the repo, cd into it
- cd into epic-mail-application
- provide necessary .env variables as stated in the .env.sample file
- run **npm test** to test all endpoints or specify a particular endpoint by specifying its test file using the -t option as in **npm test -t <filename>
None
#165906644
=> #165906644 Refactor Books Tests

test/__snapshots__/author.spec.js.snap, test/auth.spec.js, test/author.spec.js
- It contains refactor for author.spec.js
- remove mocha, chai, chai-http
- add supertest
- update test assertions for jest
``npm install``
- Launch the node server with
``npm run dev``
- To run local tests using mocha
``npm run test``
- You should have Nodejs installed
- none
=> refactor author.spec.js test

test/middleware/authenticate.spec.js
- update authenticate middleware test
- add test for isAdmin
- add extra test for isAuthenticated
- N/A
- N/A
- N/A
=> chore(test): update authenticate middleware test

.gitignore, __tests__/__snapshots__/fine.spec.js.snap, __tests__/__snapshots__/profile.spec.js.snap, __tests__/auth.spec.js, __tests__/bookrequest.spec.js, __tests__/fine.spec.js, __tests__/profile.spec.js, package.json, server/controllers/profileController.js, server/middleware/validators/fineValidator.js, server/middleware/validators/profileValidator.js, server/migrations/20190501142532_create_users_table.js, server/routes/v1/index.js, server/routes/v1/profile.js
Implements feature to update and get profile information
1. Created middleware to validate admin's Input for a new fine.
2. HAVE the following endpoint working
- GET api/v1/profile/:id
- GET api/v1/profile
- PATCH api/v1/profile
3. Wrote tests to cover the above feature.
- Clone the repo, cd into epic-mail-application
- Run the command 'npm run dev'
- Using postman get the token from the login endpoint
-  At the Authorization tab, set the type to Bearer token and put the respective token on its field.
- Test the above endpoint using postman
<a href = "https://www.pivotaltracker.com/story/show/165596321">#165596321</a>
=> #165596321:  Users should be able to create their profile

__tests__/__snapshots__/auth.spec.js.snap, __tests__/auth.spec.js, package.json, server/controllers/authController.js, server/middleware/validators/authValidator.js, server/models/User.js, server/routes/v1/auth.js, server/seed/index.js
Implements feature to add user notifications
- add endpoint for logging in users
- add seed file for populating database
- N/A
- n/a
=> # Normalize staging

__tests__/__snapshots__/fine.spec.js.snap, __tests__/__snapshots__/profile.spec.js.snap, __tests__/fine.spec.js, server/controllers/fineController.js, server/middleware/validators/profileValidator.js, server/routes/v1/fines.js, server/utils/validationUtils.js
Bug fix for fines features
- Removed the delete fine route
- Fix validation error messages
- Updated snapshot due to validation changes
- cd into the repo and provide all necessary env variables using the .env.sample file
- Install dependencies using npm install or yarn install
- Run npm run dev
- Test the endpoint "GET /api/v1/fines/<invalid Id>" using postman
<a href = "https://www.pivotaltracker.com/story/show/166035383">#166035383</a>
=> #166035383: Bug fix for fine feature

__tests__/__snapshots__/author.spec.js.snap, __tests__/__snapshots__/favourite.spec.js.snap, __tests__/books.spec.js, __tests__/favourite.spec.js, __tests__/utils/helpers.js, client/pages/Register/index.js, server/app.js, server/controllers/favouriteController.js, server/middleware/auth/authenticate.js, server/migrations/20190520120543_create_favourites_table.js, server/models/Favourite.js, server/routes/v1/favourite.js, server/routes/v1/index.js
- User can favorite author
- add controllers, models and route
- add test cases
- clone repo
- start dev server
- PT Story link - [#166116301]
=> #166116301 feat user can favourite author

client/components/Navbar/index.js
- It fixes active nav link on Navbar component 
- add NavLink from react-router
``npm install``
- Launch the node server with
``npm run dev``
Before
After
- PT Story link - `[#166226367] (https://www.pivotaltracker.com/story/show/166226367)`
=> #166226367 fix active nav link on Navbar component

client/components/Button/index.js, client/components/InputForm/index.js, client/components/Navbar/index.js, client/pages/Books/index.js, client/pages/Register/index.js, client/pages/SignIn/index.js, client/validations/Auth.js, tailwind.config.js
Fix responsive behavior in sign up and sign in pages
- Fixed input fields and label arrangement in smaller screen
- fix footer in smaller screen
- change the name of the sign in button and header
- cd into the repo and provide all necessary env variables using the .env.sample file
- Install dependencies using npm install or yarn install
- Run npm run dev or yarn run dev
- Depending on the PORT number provided in the .env file, make a request to localhost:4000/signup
- Desktop view
- Mobile view
<a href = "https://www.pivotaltracker.com/story/show/166229135">#166229135</a>
=> #166229135: Bug fix for UI sign up and sign in pages

client/components/Book/index.js, client/pages/BookDetails/index.js, client/pages/Books/index.js, client/pages/Home/index.js, client/pages/Main.js, client/pages/Register/index.js, package.json, server/public/index.html
- Add view specific book details page
- add view book route
- add view book page
- Cd into the repo
- Produce a local .env file
- Install all dependencies with `npm install` or `yarn install`
- Run seed with `npm run seed` or `yarn run seed`
- Start the server with `npm run` dev or yarn run dev
Visit `localhost:{PORT}/books`
###Any background context you want to provide?
- PT Story link - [#166199736]
=> #166199736 feat(book): View Specific Book Details

client/components/Button/index.js, client/pages/ForgotPassword/index.js, client/pages/Main.js, client/pages/ResetPassword/index.js, client/pages/SignIn/index.js, client/validations/Auth.js, server/models/User.js
Implements forgot and reset password feature UI and api consumption
- Designed UI for forgot and reset password
- implemented forgot and reset password funtionality on UI
- Added routes and validation for the forgot and reset password components
http://localhost:5000/forgot-password
http://localhost:5000/reset-password?token=<token>
None
=> #166083775 forgot and reset password UI feature and implementation

.babelrc, client/components/FineRow/index.js, client/components/sideNavbar/index.js, client/pages/BorrowedBooks/index.js, client/pages/Fines/index.js, client/pages/Main.js
- Design get user fines UI
- add Fines dashboard page
- add Fines route
- Cd into the repo
- Produce a local .env file
- Install all dependencies with `npm install` or `yarn install`
- Run seed with `npm run seed` or `yarn run seed`
- Start the server with `npm run` dev or yarn run dev
Visit `localhost:{PORT}/fines`
- PT Story link - [#166253724]
=> #166253724 Get user fines UI

client/components/Toaster/index.js, client/context/toastContext.js, client/pages/ForgotPassword/index.js, client/pages/Home/index.js, client/pages/Main.js, client/pages/ResetPassword/index.js
Implements toast messages
- Implemented toast message
- Created toast message context
- Encapsulated all component into toast provider in Main
- Created Toaster Component
- Utilized the toast message in ForgotPassword and ResetPassword
import `ToastContext`
get the `showToast` Method
call `showToast` method and pass in message type and the message as arguments
Example
```
import context from '@context/toastContext';
const { ToastContext } = context;
const [toast, showToast] = useContext(ToastContext);
showToast(type, message)
```
**NB** type can either be `error` or ```success```
None
None
=> #166254002 toast message implementation

client/components/AdminSideNav/index.js, client/context/toastContext.js, client/pages/BookDetails/index.js, client/pages/Fines/index.js, client/pages/ForgotPassword/index.js, client/pages/Main.js, client/pages/Profile/index.js, client/pages/Register/index.js, client/pages/ResetPassword/index.js, client/pages/SignIn/index.js
- stabilize app 
- Add Toaster to app
- add adminRoute
- client side view restriactions
- clone repo
- start dev server
- PT Story link - [#166268995]
=> #166268995 chore(normalise) : stabelize app

__tests__/__snapshots__/books.spec.js.snap, __tests__/books.spec.js, __tests__/utils/helpers.js, server/controllers/bookController.js, server/middleware/book/bookRequest.js, server/migrations/20190525151105_alter_lending_requests.js, server/routes/v1/books.js
Removes the Admin approval for User borrow request
- User can get available books once all obligations have been fulfilled
- Remove Admin approval to borrow books
- Removed approved date and status column from lending_requests table
- Adds timesExtended column to the lending_requests table
- Adds constraint to the maximum number of times a book can be extended
- Adds constraint to the maximum number of days a book can be extended
- Removes all tests for admin approval of borrow requests
- Adds tests for borrow constraints (number of days and times for book extension)
- Edits borrowedBooks method on books controller by substituting _status_ for _returned_ in query
- Cd into the repo and create a .env file using the .env.sample file in the root directory
- Install all …
=> #166253917 Implement feedback on borrow requests

client/components/AdminSideNav/index.js, client/components/BorrowedBookRow/index.js, client/components/IsLoggedIn/index.js, client/components/Tablecontent/index.js, client/context/authContext.js, client/pages/BorrowedBooks/index.js, client/pages/Fines/index.js, client/pages/Main.js, client/pages/Profile/index.js, client/pages/Register/index.js, server/controllers/bookController.js, server/controllers/profileController.js, server/middleware/book/bookRequest.js, server/migrations/20190525151105_alter_lending_requests.js, server/routes/v1/books.js, tailwind.config.js
Set up modal component for admin add book page
- Fix bug all borrowed books page
- modify all borrowed books to use modal component
- authenticate add a book route
- cd into the repo and provide all necessary env variables using the .env.sample file
- Install dependencies using npm install or yarn install
- Run npm run dev or yarn run dev
- Depending on the PORT number provided in the .env file, make a request to localhost:4000/borrowed
<a href = "https://www.pivotaltracker.com/story/show/ 166253088"> #166253088</a>
=>  #166253088 : Fix borrow books modal

client/components/Book/index.js, client/components/IsLoggedIn/index.js, client/components/TableRow/index.js, client/context/authContext.js, client/pages/AdminBooksDashboard/index.js, client/pages/BookDetails/index.js, client/pages/Books/index.js, client/pages/Register/index.js, client/utils/index.js, server/controllers/bookController.js, server/middleware/auth/authenticate.js, server/middleware/book/bookRequest.js, server/middleware/validators/bookValidator.js, server/models/Book.js, server/routes/v1/books.js
User can pay to borrow a book from the library
- User should be able to borrow a book and pay for such book
- Cd into it
- Make a copy of the .env.sample file and create all needed variables
- Install all dependencies with **yan install** or **npm intsall**
- Run migrations with **knex migrate:latest**
- Run localhost with the port on your .env
- Now you can sign and borrow the book Yippeee!!
Ensure that all required data are provided to avoid validation error
#166257742
=> #166257742 User can Borrow a book and Pay using PayStack
